### ISSUE TITLE
방학4주차 - 백준 1753, 최단경로 시간초과 

### ISSUE THREAD

**Issue by Hong-JinSuk** [IamJunhaHwang/Alkkagi_Algorithm_Studygroup#10]
#include<iostream>
#include<queue>
#include<vector>
#define INF 987654321

using namespace std;

int V, E, Start;
int Dist[20001]; // value

vector<pair<int, int>> Route[20001]; // node
priority_queue<pair<int, int>, vector<pair<int, int> >, greater<pair<int, int> > >pq;

void Search(int start) {

	// start 삽입
	pq.push(make_pair(0, start));

	while (!pq.empty()) {

		// 현재 까지 코스트
		int cur_cost = pq.top().first; // x

		// 현재 노드
		int current = pq.top().second; // U

		// 현재노드 정보 queue에서 제거
		pq.pop();

		// 현재 노드와 이어진 모든 노드 검사
		for (int i = 0; i < Route[current].size(); i++) {
			// 순서대로 다음 노드 정보
			int next = Route[current][i].first; // V

			// 다음 노드까지의 비용 = 현재노드비용 + 현재에서 다음노드의 비용
			int next_Dist = cur_cost + Route[current][i].second; // x+W

			// 비용이 더 작다면 교체, 비용과 다음노드 삽입
			if (Dist[next] > next_Dist) {
				Dist[next] = next_Dist;
				pq.push(make_pair(next_Dist, next));
			}
		}
	}
}

int main() {

	cin >> V >> E >> Start;

	for (int i = 0; i < E; i++) {
		int start, end, cost;
		cin >> start >> end >> cost;

		Route[start].push_back(make_pair(end, cost));
	}

	// 모든 노드 까지의 Cost를 INF로 바꿔줌
	for (int i = 1; i < V + 1; i++) Dist[i] = INF;

	// 자기 자신은 0
	Dist[Start] = 0;

	Search(Start);

	for (int i = 1; i < V + 1; i++) {
		if (Dist[i] == INF) cout << "INF\n";
		else cout << Dist[i] << endl;
	}

	return 0;
}

로 짯는데, 시간초과가 뜹니다. 그런데 구글링해보니깐 저랑 거의 똑같은 코드가 있는데 이건 제출해보니깐 정답이 되네요?? 어디가 문제일까용 함수이름이 다른 부분은 옆에 주석처리로 해놨슴돠.

https://rujang.tistory.com/entry/%EB%B0%B1%EC%A4%80-1753%EB%B2%88-%EC%B5%9C%EB%8B%A8%EA%B2%BD%EB%A1%9C-CC

가 제 코드랑 거의 유사한 코드입니돠

**Comment by IamJunhaHwang** [comment]
https://www.acmicpc.net/problem/15552

위에서 설명하는 것 먼저 적용해보시죠

**Comment by IamJunhaHwang** [comment]
똑같은 코드라는 사이트 보니까 저분은 printf, scanf 사용했네

아마 위에 올려놓은거 적용시키면 AC 받을 듯 하네요

**Comment by Hong-JinSuk** [comment]
똑같이 시간초과 납니다 후,,,

**Comment by Hong-JinSuk** [comment]
나중에 따로 해결해 볼게요오...
