### ISSUE TITLE
앞으로 계획

### ISSUE THREAD

**Issue by Hong-JinSuk** [IamJunhaHwang/Alkkagi_Algorithm_Studygroup#4]
## 벌금
* 매주 안 풀어오면 1000~5000 사이로 돈을 모으고, 기말고사 끝나고 회식
1-1. 1000원
1-2. 2000
1-3. 3000
1-4. 4000
1-5. 5000

_____

## 문제선정 난이도
* 어디부터 시작하면 좋을지 정해주세요.
2-1. 실버3
2-2. 실버2
2-3. 실버1
2-4. 골드5
2-5. 기타

-----

## 문제선정 사이트 및 순서
* 순서 정하죵
3-1. 준하가 계속 내줬으면 좋겠다!!! (강추 👍 )
3-2. 매주 룰렛
3-3. 순서 정해서 딱!!

**Comment by Hong-JinSuk** [comment]
1-3. 2-3, 3-1

**Comment by IamJunhaHwang** [comment]
1-2

2-3

3-3

**Comment by ByeongJun-Jang** [comment]
1 - 1
2 - 3
3 - 3

**Comment by kgeunwo77** [comment]
1 - 2
2 - 2
3 - 3

**Comment by sdlee130** [comment]
1-1
2-4
3-1

**Comment by kiw331** [comment]
1-3
2-3
3-2

**Comment by stoneTiger0912** [comment]
1-2
2-3
3-1

**Comment by jinbong-yeom** [comment]
1-1
2-3
3-3(1도 괜춘 ㅋㅋ)

**Comment by IamJunhaHwang** [comment]
- 최종 결과

  - **1-1 벌칙금: 1000원**

  - **2-3 문제 난이도: 실버 1**
  -  **3-3 문제 선정 순서: 순서 정한 후돌아가면서**
