### ISSUE TITLE
피자굽기 문제 틀린이유

### ISSUE THREAD

**Issue by Hong-JinSuk** [IamJunhaHwang/Alkkagi_Algorithm_Studygroup#7]
#include<iostream>
#include<vector>

using namespace std;

int d, n;
vector<int> Oven;
vector<int> Pizza;

int main() {

	cin >> d >> n;

	int num;
	Oven.push_back(NULL); // 그냥 1부터 넣고 싶어서...
	for (int i = 1; i < d+1; i++) {
		cin >> num;
		Oven.push_back(num);
	}

	for (int i = 0; i < n; i++) {
		cin >> num;
		Pizza.push_back(num);
	}

	for (int i = 1; i < d + 1; i++) {
		// 어차피 아래가 커봤자 위에서 내려가면 다 내려가짐
		if (i == d) break;
		if (Oven[i + 1] > Oven[i]) Oven[i + 1] = Oven[i];
	}

	int Loc = d;
	for (int j = 0; j < n; j++) {
		int cnt = 0;
		for (int i = d; i > 0; i--) {
			//cout << "i : " << i << endl;
			cnt++;
			if (Pizza[j] <= Oven[i]) { //피자가 i까지 내려가면
				//cout << "cnt : " << cnt << endl;
				Loc -= cnt;
				d = i - 1;
				break; // 다음피자로
			}
			if (i == 1) {
				Loc = -1;
				d = 1;
			}
		}
	}

	cout << Loc + 1;

	return 0;
}

으로 했는데, 틀렸습니다가 뜨는데,,, 왜 안될까요...오?

**Comment by sdlee130** [comment]
피자가 2에 들어간 뒤에 1에도 들어가고 프로그램이 끝날 때, 정답이 1이 나와야 되는데 이 경우 d가 1이 되니까 아래 조건문을 돌아서 정답이 0으로 나오는 거 같음
```
		if (i == 1) {
			Loc = -1;
			d = 1;
		}
'''

**Comment by sdlee130** [comment]
피자가 2에 들어가고 1에 들어간 다음에 피자를 더 넣어야 되는데 못 넣으면 0이 되야 하는데 이 경우에 피자가 1에 들어간 다음에 d가 0이 되어서 반복문을 아예 안 도니까 그 밑에 Loc를 바꿔주는 조건문을 안 돌고 프로그램이 종료되니까 출력이 1이 될 거 같음 정답은 0이 되어야 함

**Comment by Hong-JinSuk** [comment]
오오 확인했고 고치니 맞네요 ㄳㄳ
