### ISSUE TITLE
오늘도 어김없이 돌아온 오류 - 백준13269, 쌓기나무

### ISSUE THREAD

**Issue by Hong-JinSuk** [IamJunhaHwang/Alkkagi_Algorithm_Studygroup#9]
#include<iostream>
#include<vector>
using namespace std;

int n, m;

int main() {

	cin >> n >> m;
	
	vector<vector<int>> Block(n, vector<int>(m, 0));

	for (int i = 0; i < n; i++) {
		for (int j = 0; j < m; j++) {
			int num;
			cin >> num;
			Block[i][j] = num;
		}
	}

	for (int i = 0; i < m; i++) {
		int num;
		cin >> num;
		for (int j = 0; j < n; j++) {
			// 0이 아니면 앞에서 본 모양으로 꽉 채워줌 
			if (Block[j][i] != 0) Block[j][i] = num;
		}
	}

	for (int i = n - 1; n >=0 ; i--) {
		int num;
		cin >> num;
		for (int j = 0; j < m; j++) {
			if (Block[i][j] != 0) {
				// 최대값보다 크다면 최대값으로 맞춰준다.
				if (num < Block[i][j]) Block[i][j] = num;
			}
		}
		if (i == 0) break; // 왜 알아서 못나가지? ㅋㅋㅋㅋ
	}

	for (int i = 0; i < n; i++) {
		for (int j = 0; j < m; j++) {
			cout << Block[i][j] << " ";
		}
		cout << endl;
	}

	return 0;
}

80%도 넘어가는데 야무지게 틀렸습니다!! 하는데 반례도 다 야무지게 잘되고 사실 틀린 이유를 감도 못잡겠는게 더 문제인 상황... 아무거나 넣어봐도 다 잘 나오는데 허허,,,

**Comment by kiw331** [comment]
틀린 입력 들어왔을 때 -1 출력이 안되는거 같습니다.

반례
1 1
0 
0 
1

**Comment by IamJunhaHwang** [comment]
정신 안차려!! 문제 조건 확인 안해?!?!?!

**Comment by Hong-JinSuk** [comment]
ㅈㅅㅈㅅ 그렇네요... 하하하
